version: "3"
services:
  database:
      container_name: postgres-datmsc1
      image: postgres:latest
      -:
        - 5432:5432
      volumes:
        - /users/Daniel Owolabi/data/postgres/ datmsc1:/postgres
      env_file:
        - datmsc1.env
